name: FeatherJoinDate
version: '${project.version}'
main: dev.zerek.featherjoindate.FeatherJoinDate
api-version: 1.20
authors: [ Zerek ]
depend:
  - PremiumVanish
description: Stores player first join date  - not reset with seasons.
commands:
  seen:
    description: View firstjoin dates.
